# Generated by Django 3.0.7 on 2020-08-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(max_length=15)),
                ('UID', models.CharField(max_length=15)),
                ('records', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('record_status', models.IntegerField(default=0)),
                ('savepath', models.CharField(default='.', max_length=100)),
                ('port', models.CharField(default='8000', max_length=8)),
                ('monitorPID', models.CharField(default='0', max_length=10)),
                ('streamlinkPID', models.CharField(default='0', max_length=10)),
                ('command', models.IntegerField(default=0)),
            ],
        ),
    ]
