# Generated by Django 3.0.7 on 2020-07-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='record_status',
            field=models.BooleanField(default=False),
        ),
    ]
