# Generated by Django 3.0.7 on 2020-07-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0002_config_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='savepath',
            field=models.CharField(default='.', max_length=100),
        ),
    ]
