# Generated by Django 3.0.7 on 2020-07-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0003_config_savepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='UID',
            field=models.CharField(default='', max_length=15),
        ),
    ]
