# Generated by Django 3.0.7 on 2020-07-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0004_config_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='UID',
            field=models.CharField(max_length=15),
        ),
    ]
