# Generated by Django 3.0.7 on 2020-07-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0005_auto_20200731_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='record_status',
            field=models.IntegerField(default=0),
        ),
    ]
