# Generated by Django 3.0.7 on 2020-08-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0007_config_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='monitorPID',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
