# Generated by Django 3.0.7 on 2020-08-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0008_config_monitorpid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='monitorPID',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
