# Generated by Django 3.0.7 on 2020-08-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0009_auto_20200802_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='streamlinkPID',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='config',
            name='monitorPID',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
