# Generated by Django 3.0.7 on 2020-07-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Cover', models.CharField(max_length=100)),
                ('Date', models.DateField(max_length=10)),
                ('Time', models.CharField(max_length=20)),
                ('Resolution', models.CharField(max_length=20)),
                ('FrameRate', models.IntegerField()),
                ('VideoByteRate', models.IntegerField()),
                ('AudioByteRate', models.IntegerField()),
            ],
        ),
    ]
